db:
  image: mongo
  ports:
    - "27017:27017"
  command: "--smallfiles --logpath=/dev/null"

web:
  build: .
  command: node server.js
  volumes:
    - .:/app
  ports:
    - "80:8080"
  links:
    - db
  environment:
    PORT: 8080 # this is optional, allows express to use process.env.PORT instead of a raw 3000
